sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - develop
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: develop
  local-dir: public
  target_branch: master
